// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/stratalink-hero/CinematicDeep.tsx": () => import("../components/mockups/stratalink-hero/CinematicDeep.tsx"),
  "./components/mockups/stratalink-hero/PrecisionGrid.tsx": () => import("../components/mockups/stratalink-hero/PrecisionGrid.tsx"),
  "./components/mockups/stratalink-hero/TerminalDark.tsx": () => import("../components/mockups/stratalink-hero/TerminalDark.tsx")
};
