import os


def render_markdown(data):
    """
    Render the daily summary as a Markdown file.
    """
    output_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    md_path = os.path.join(output_dir, "output", "daily_summary.md")
    
    os.makedirs(os.path.dirname(md_path), exist_ok=True)

    with open(md_path, "w") as f:
        f.write(f"# STRATA – Daily Crypto Market Structure Summary\n")
        f.write(f"### {data['date']}\n\n")

        f.write("---\n\n")

        f.write("## STRATA Summary\n\n")
        f.write(f"**Dominant Factor:** {data['summary']['dominant_factor']}\n\n")
        f.write(f"**Regime:** {data['summary']['regime_sentence']}\n\n")

        f.write("---\n\n")

        f.write("## Market Snapshot\n\n")
        f.write("| Metric | Value |\n")
        f.write("|--------|-------|\n")
        f.write(f"| BTC Price | ${data['snapshot']['btc_price']:,.2f} |\n")
        f.write(f"| ETH Price | ${data['snapshot']['eth_price']:,.2f} |\n")
        f.write(f"| SOL Price | ${data['snapshot']['sol_price']:,.2f} |\n")
        f.write(f"| Total Market Cap | ${data['snapshot']['total_market_cap']:,.0f} |\n")
        f.write(f"| 24h Liquidations | ${data['snapshot']['liquidations_24h']:,.0f} |\n")
        f.write(f"| Breadth Positive | {data['snapshot']['breadth_positive']} |\n")
        f.write(f"| Breadth Negative | {data['snapshot']['breadth_negative']} |\n")
        f.write("\n")

        f.write("---\n\n")

        f.write("## Liquidity Microstructure\n\n")
        liquidity = data['drivers']['liquidity_micro']
        f.write(f"- **Depth Change:** {liquidity['depth_change']}\n")
        f.write(f"- **Orderbook Imbalance:** {liquidity['orderbook_imbalance']}\n")
        f.write(f"- **Spreads:** {liquidity['spreads']}\n")
        f.write(f"- **CEX vs DEX:** {liquidity['cex_vs_dex']}\n")
        f.write(f"- **Stablecoin Rotation:** {liquidity['stablecoin_rotation']}\n")
        f.write("\n")

        f.write("---\n\n")

        f.write("## Flows & Positioning\n\n")
        flows = data['drivers']['flows_positioning']
        f.write(f"- **Basis:** {flows['basis']}\n")
        f.write(f"- **Funding Rates:** BTC: {flows['funding']['btc']}, ETH: {flows['funding']['eth']}, SOL: {flows['funding']['sol']}\n")
        f.write(f"- **Liquidations:** Long: ${flows['liquidations']['long_liq']:,}, Short: ${flows['liquidations']['short_liq']:,}\n")
        f.write("\n")

        f.write("---\n\n")

        f.write("## On-Chain Activity\n\n")
        onchain = data['drivers']['onchain']
        f.write(f"- **TX Activity:** {onchain['tx_activity']}\n")
        f.write(f"- **Whale Behavior:** {onchain['whale_behavior']}\n")
        f.write(f"- **Velocity/NVT:** {onchain['velocity_nvt']}\n")
        f.write("\n")

        f.write("---\n\n")

        f.write("## Sector Performance\n\n")
        f.write(f"**Leaders:** {', '.join(data['leaders'])}\n\n")
        f.write(f"**Laggards:** {', '.join(data['laggards'])}\n\n")

        f.write("---\n\n")

        if data['events']:
            f.write("## Key Events\n\n")
            for event in data['events']:
                f.write(f"- {event}\n")
            f.write("\n")

        f.write("---\n\n")

        f.write("## Closing Note\n\n")
        f.write(f"{data['closing_note']}\n\n")

        f.write("---\n\n")
        f.write("*Generated by STRATA Daily Engine*\n")

    print(f"Markdown summary written to {md_path}")
